# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', models.BigIntegerField(null=True)),
                ('password', models.CharField(max_length=10)),
                ('location', models.CharField(default=None, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.FloatField(null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('category', models.CharField(max_length=25)),
                ('sub_category', models.CharField(max_length=25)),
                ('brand', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='static/Images')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/OffersImages')),
                ('url', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.PositiveIntegerField(null=True)),
                ('customer_name', models.CharField(max_length=25)),
                ('customer_address', models.TextField()),
                ('item_list', jsonfield.fields.JSONField(default={})),
                ('amount', models.FloatField(null=True)),
                ('status', models.CharField(max_length=10)),
                ('delivery_type', models.CharField(default='cod', max_length=4)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_boy', models.CharField(default=None, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('sub_category_name', models.TextField()),
                ('image', models.ImageField(default='static/CatImages/default_cat_icon.png', upload_to='static/CatImages')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', models.BigIntegerField(null=True)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=10)),
                ('cart', jsonfield.fields.JSONField(default={})),
            ],
        ),
    ]
