# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_boy',
            field=models.CharField(default=' ', max_length=25),
        ),
    ]
