# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171214_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
