# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171215_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.FloatField(null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('category', models.CharField(max_length=25)),
                ('sub_category', models.CharField(max_length=25)),
                ('brand', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='Images')),
            ],
        ),
    ]
