# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.PositiveIntegerField(null=True)),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_address', models.TextField()),
                ('amount', models.FloatField(null=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
