# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_list',
            field=models.TextField(null=True),
        ),
    ]
