# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20171216_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cart',
            field=models.TextField(),
        ),
    ]
