# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20171216_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='OffersImages')),
                ('url', models.CharField(max_length=20)),
            ],
        ),
    ]
