# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 07:04
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_offers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offers',
            new_name='Offer',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='order',
            name='item_list',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
