# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_structure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='category',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='structure',
            old_name='sub_category',
            new_name='sub_category_name',
        ),
    ]
