# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20171227_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='image',
            field=models.ImageField(default='CatImages/default_cat_icon.png', upload_to='CatImages'),
        ),
    ]
