# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_structure_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(default='cod', max_length=4),
        ),
    ]
