# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_order_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='static/Images'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(upload_to='static/OffersImages'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(default='cod3', max_length=4),
        ),
        migrations.AlterField(
            model_name='structure',
            name='image',
            field=models.ImageField(default='static/CatImages/default_cat_icon.png', upload_to='static/CatImages'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
